### ISSUE TITLE
Purchase pending after 6 days, money already left bank account

### ISSUE THREAD

**Issue by zv0n** [numixproject/numix-store#8]
So I've made a purchase on the 15th April and the order is still displayed as "pending". I payed using paypal and the money already left my bank account yesterday. Is this a bug or is it supposed to take this long for an order to process?

**Comment by Foggalong** [comment]
Hi can you send us an email at numixproject@gmail.com - we can't address issues relating to purchases through Github since the contents of discussion will often include private information.
